spring.application.name=price-tracker

server.port=7777

# API Prefix
server.servlet.contextPath=/api

# DB Credentials
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password

# Show SQL in console
spring.jpa.show-sql=true
# Update DB with DDL
spring.jpa.hibernate.ddl-auto=create
# Specify schema
spring.jpa.properties.hibernate.default_schema=price-tracker