create table prices (
    amount float(53) not null,
    price_id integer generated by default as identity,
    product_id integer,
    created_at timestamp(6) not null,
    price_ended timestamp(6),
    price_started timestamp(6),
    updated_at timestamp(6) not null,
    currency varchar(255),
    description varchar(255),
    primary key (price_id)
);

create table products (
    product_id integer generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    link varchar(255),
    name varchar(255) not null,
    store varchar(255),
    primary key (product_id)
);

alter table if exists prices
add constraint fk_prices_product_id
foreign key (product_id)
references products;
